export default function ResourcesPage() {
    return (
        <div className="max-w-4xl mx-auto py-12 space-y-16">
            {/* Header */}
            <section className="space-y-4">
                <h1 className="text-5xl md:text-7xl font-black uppercase tracking-tighter leading-none border-b-8 border-black pb-6">
                    FOIA Resources
                </h1>
                <p className="text-lg font-medium">
                    Everything you need to request ALPR records and expose surveillance infrastructure.
                </p>
            </section>

            {/* Washington Precedent Banner */}
            <section className="bg-yellow-300 border-4 border-black p-6 brutal-shadow">
                <div className="flex items-start gap-4">
                    <span className="text-4xl">⚖️</span>
                    <div>
                        <h2 className="text-2xl font-black uppercase mb-2">Legal Precedent Established</h2>
                        <p className="font-medium mb-4">
                            On November 6, 2024, a Washington State Superior Court judge ruled:
                        </p>
                        <blockquote className="border-l-4 border-black pl-4 italic font-bold text-lg mb-4 bg-white p-4">
                            &quot;Images generated by flock cameras are public records under Washington state law
                            and they are not exempt from disclosure.&quot;
                        </blockquote>
                        <div className="text-sm space-y-2">
                            <p><strong>Key findings:</strong></p>
                            <ul className="list-disc list-inside space-y-1 ml-4">
                                <li>ALPR data qualifies as public records</li>
                                <li>Agencies cannot claim exemption</li>
                                <li>Data doesn&apos;t need to be &quot;possessed&quot; by agency to be subject to disclosure</li>
                            </ul>
                            <p className="mt-4 pt-4 border-t border-black border-dotted">
                                This precedent confirms ALPR data qualifies as public records. Agencies cannot claim exemption.
                            </p>
                        </div>
                    </div>
                </div>
            </section>

            {/* Supporting Legal Action */}
            <section className="space-y-6 border-2 border-black p-6 bg-white brutal-shadow">
                <h2 className="text-3xl font-black uppercase tracking-tight">Supporting Legal Action</h2>
                <div className="prose-lg font-medium leading-relaxed space-y-4">
                    <p>
                        The <strong>Institute for Justice</strong> is challenging mass ALPR surveillance in Norfolk, VA.
                    </p>
                    <p>
                        Dr. John Padfield is writing a pro bono amicus brief analyzing deficiencies in ALPR policy manuals nationwide.
                    </p>
                    <div className="bg-gray-50 p-4 border-l-4 border-black font-bold">
                        <p>Your submissions help build the case:</p>
                        <ul className="list-disc list-inside space-y-1 ml-4 text-sm mt-2">
                            <li>Document lack of policies</li>
                            <li>Show training gaps</li>
                            <li>Expose unauthorized access</li>
                        </ul>
                    </div>
                    <a href="https://ij.org" target="_blank" rel="noopener noreferrer" className="inline-block mt-4 brutal-btn text-sm">
                        Learn About the Institute for Justice →
                    </a>
                </div>
            </section>

            {/* Request Templates */}
            <section className="space-y-8">
                <h2 className="text-3xl font-black uppercase tracking-tight border-b-4 border-black pb-2">
                    Request Templates
                </h2>

                {/* Template 1 */}
                <div className="border-2 border-black p-6 space-y-4">
                    <h3 className="text-xl font-black uppercase">Template 1: ALPR Contracts &amp; Policies</h3>
                    <p className="text-sm text-gray-700">
                        Request all contracts with ALPR vendors, policy/procedure manuals, training documentation, and audit procedures.
                    </p>
                    <details className="bg-gray-100 border border-black">
                        <summary className="p-4 font-bold cursor-pointer hover:bg-gray-200">View Template Text</summary>
                        <pre className="p-4 text-xs font-mono whitespace-pre-wrap bg-white border-t border-black overflow-x-auto">
                            {`[Your Name]
[Your Address]
[Date]

[Agency Name]
[Agency Address]

RE: Public Records Request – ALPR/Flock Camera Systems

Dear Public Records Officer,

Pursuant to the [State] Public Records Act, I am requesting the following records related to Automatic License Plate Reader (ALPR) systems operated by or on behalf of your agency:

1. All contracts, agreements, memoranda of understanding, or other documents between your agency and Flock Safety, Vigilant Solutions, or any other ALPR vendor.

2. All policies, procedures, and guidelines governing the use of ALPR systems.

3. All training materials provided to personnel with access to ALPR data.

4. All audit logs showing who has accessed the ALPR system in the past 12 months.

5. Total cost of ALPR system implementation and ongoing maintenance.

I request that responsive records be provided electronically in their native format.

Thank you for your prompt attention to this request.

Sincerely,
[Your Name]`}
                        </pre>
                    </details>
                </div>

                {/* Template 2 */}
                <div className="border-2 border-black p-6 space-y-4 bg-red-50">
                    <div className="flex items-center gap-2">
                        <span className="text-2xl">🔥</span>
                        <h3 className="text-xl font-black uppercase">Template 2: Public Official Vehicle Tracking</h3>
                    </div>
                    <p className="text-sm font-bold text-red-800">
                        ONLY FOR THE BOLD — Based on Washington State court ruling (Nov 2024)
                    </p>
                    <p className="text-sm text-gray-700">
                        Request vehicle location history for specific public officials. Cite the Washington precedent. Limit to government-owned vehicles.
                    </p>
                    <details className="bg-white border border-black">
                        <summary className="p-4 font-bold cursor-pointer hover:bg-gray-100">View Template Text</summary>
                        <pre className="p-4 text-xs font-mono whitespace-pre-wrap bg-white border-t border-black overflow-x-auto">
                            {`[Your Name]
[Your Address]
[Date]

[Agency Name]
[Agency Address]

RE: Public Records Request – Vehicle Location Data for Public Officials

Dear Public Records Officer,

Pursuant to the [State] Public Records Act, and consistent with the November 6, 2024 Washington State Superior Court ruling establishing that ALPR data constitutes public records, I am requesting the following:

1. All ALPR/Flock camera detection records for the following government-owned vehicles:
   - [Vehicle License Plate 1] assigned to [Official Name/Title]
   - [Vehicle License Plate 2] assigned to [Official Name/Title]

2. Date range: [Start Date] to [End Date]

3. For each detection, please provide:
   - Date and time
   - Camera location
   - Direction of travel (if available)

Legal Basis:
The Washington State ruling confirmed that "images generated by flock cameras are public records under Washington state law and they are not exempt from disclosure."

Public servants operate government vehicles in their public capacity. This data is not exempt from disclosure.

I request that responsive records be provided electronically.

Sincerely,
[Your Name]`}
                        </pre>
                    </details>
                </div>
            </section>

            {/* State Guide */}
            <section className="space-y-8">
                <h2 className="text-3xl font-black uppercase tracking-tight border-b-4 border-black pb-2">
                    State-by-State Guide
                </h2>

                <div className="grid md:grid-cols-2 gap-6">
                    <div className="border-2 border-black p-6 bg-green-50">
                        <h3 className="font-black uppercase mb-4 flex items-center gap-2">
                            <span>🏆</span> Tier 1: Strongest Laws
                        </h3>
                        <ul className="space-y-2 font-mono text-sm">
                            <li className="flex items-center gap-2"><span className="text-green-600 font-bold">✓</span> Connecticut</li>
                            <li className="flex items-center gap-2"><span className="text-green-600 font-bold">✓</span> Missouri</li>
                            <li className="flex items-center gap-2"><span className="text-green-600 font-bold">✓</span> North Carolina</li>
                            <li className="flex items-center gap-2"><span className="text-green-600 font-bold">✓</span> Florida</li>
                        </ul>
                        <p className="mt-4 text-xs text-gray-600">
                            These states have the most citizen-friendly open records laws. Start here if you can.
                        </p>
                    </div>

                    <div className="border-2 border-black p-6 bg-yellow-50">
                        <h3 className="font-black uppercase mb-4 flex items-center gap-2">
                            <span>⚖️</span> Recent Victory
                        </h3>
                        <ul className="space-y-2 font-mono text-sm">
                            <li className="flex items-center gap-2"><span className="text-yellow-600 font-bold">★</span> Washington (Nov 2024)</li>
                        </ul>
                        <p className="mt-4 text-xs text-gray-600">
                            Court ruled ALPR data = public records. Agencies cannot claim exemption.
                        </p>
                    </div>
                </div>
            </section>

            {/* Known Policy Failures */}
            <section className="space-y-8">
                <h2 className="text-3xl font-black uppercase tracking-tight border-b-4 border-black pb-2">
                    Known Policy Failures
                </h2>
                <p className="text-gray-700">
                    Upload FOIA results showing similar failures to strengthen legal challenges nationwide.
                </p>

                <div className="border-2 border-black p-6 space-y-4 bg-gray-100">
                    <h3 className="font-black uppercase">Los Angeles Police Department</h3>
                    <p className="text-xs uppercase font-bold text-gray-500">Source: California State Auditor</p>
                    <ul className="space-y-2 text-sm font-medium">
                        <li>→ Staff with <strong>no ALPR duties</strong> had system access</li>
                        <li>→ <strong>No training required</strong> before granting access</li>
                        <li>→ Systematic <strong>policy violations</strong></li>
                    </ul>
                    <p className="text-xs mt-4 border-t border-black pt-4">
                        Your jurisdiction likely has similar gaps. Document them.
                    </p>
                </div>
            </section>

            {/* Pipeline */}
            <section className="bg-black text-white p-8 brutal-shadow-white space-y-6">
                <h2 className="text-3xl font-black uppercase tracking-tight text-white border-b-2 border-white pb-2 inline-block">
                    The Accountability Pipeline
                </h2>
                <div className="grid md:grid-cols-3 gap-6 text-center">
                    <div className="space-y-2">
                        <span className="text-4xl">📍</span>
                        <h3 className="font-bold uppercase text-yellow-300">Step 1: Map</h3>
                        <p className="text-sm text-gray-300">DFlock.me maps ALPR camera locations (80,000+ documented)</p>
                        <a href="https://dflock.me" target="_blank" rel="noopener noreferrer" className="inline-block mt-2 text-xs underline text-yellow-300 hover:text-white">
                            Visit DFlock →
                        </a>
                    </div>
                    <div className="space-y-2">
                        <span className="text-4xl">📄</span>
                        <h3 className="font-bold uppercase text-yellow-300">Step 2: FOIA</h3>
                        <p className="text-sm text-gray-300">Request policies, contracts, and tracking data using our templates</p>
                        <a href="#" className="inline-block mt-2 text-xs underline text-yellow-300 hover:text-white">
                            Templates Above ↑
                        </a>
                    </div>
                    <div className="space-y-2">
                        <span className="text-4xl">📊</span>
                        <h3 className="font-bold uppercase text-yellow-300">Step 3: Track</h3>
                        <p className="text-sm text-gray-300">Upload your results to publicrecord.fyi for public accountability</p>
                        <a href="/upload" className="inline-block mt-2 text-xs underline text-yellow-300 hover:text-white">
                            Submit Records →
                        </a>
                    </div>
                </div>
                <p className="text-center text-sm text-gray-400 pt-4 border-t border-gray-800">
                    We&apos;re all part of the same movement.
                </p>
            </section>

            {/* CTA */}
            <section className="text-center space-y-6 py-8">
                <p className="text-xl font-bold">Ready to file a request?</p>
                <div className="flex flex-wrap justify-center gap-4">
                    <a href="/upload" className="brutal-btn">Submit Your FOIA Results</a>
                </div>
            </section>
        </div>
    );
}
